### ISSUE TITLE
JS_Parse_Error if a JS file contains '$' character

### ISSUE THREAD

**Issue by jdecool** [Sjeiti/grunt-include-file#3]
When I try to include a file that contains the `'$'` string, the script trigger an error `JS_Parse_Error`.

A sample of my included file :

``` javascript
MyComponent.Currencies = {
  EUR: '€',
  USD: '$'
}
```

**Comment by Sjeiti** [comment]
I cannot reproduce this. I tried by running the test with a $ added to test/fixtures/file3.js and it runs fine.
Could you fork/branch this and create a reproduceable example (preferably as regression test).

**Comment by jdecool** [comment]
I have create a Gist with the modified file3.js and the test output:
https://gist.github.com/jdecool/778afa128f5fa7a887c6978b9eddd212

Some information about my system :
- MacOS X 10.12 (Sierra)
- Node v6.5.0
- NPM 3.10.8

Also test on Linux (Fedora) with the same result.

**Comment by Sjeiti** [comment]
Ah... I see it now... fixed for v0.1.3
I really should fix the rest of this code but I don't use Grunt anymore

**Comment by jdecool** [comment]
It's OK ! 👍 

Thanks.
